name: 功能建议
description: 提出新功能或改进建议
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        欢迎提出建议！请描述你的想法。

  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 你希望添加什么功能？
      placeholder: 例如：支持自动赠送好友花朵
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 使用场景
      description: 为什么需要这个功能？解决什么问题？
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 你是否考虑过其他实现方式？

  - type: dropdown
    id: scope
    attributes:
      label: 涉及模块
      multiple: true
      options:
        - 农场 (farm)
        - 好友 (friend)
        - 任务 (task)
        - UI 面板
        - HTTP API
        - 登录 / 协议
        - 其他
